name: Build Custom Linux Mint - Tran Huu 1952

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Linux Mint ISO
        run: |
          sudo apt update
          sudo apt install -y wget
          wget -O TranHuu1952-Linux.iso https://mirrors.edge.kernel.org/linuxmint/stable/21.3/linuxmint-21.3-cinnamon-64bit.iso

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TranHuu1952-Linux-ISO
          path: ./TranHuu1952-Linux.iso
